// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MsgID

typedef GPB_ENUM(MsgID) {
  MsgID_SystemNot = 0,
  MsgID_SendMsg = 1,
  MsgID_StartEndLive = 2,
  MsgID_LiveConnect = 3,
  MsgID_LivePk = 4,
  MsgID_ConnectVideo = 5,
  MsgID_Disconnect = 6,
  MsgID_KyGame = 7,
  MsgID_LotteryBet = 8,
  MsgID_LotteryOpenAward = 9,
  MsgID_MoneyChange = 10,
  MsgID_LotteryDividend = 11,
  MsgID_LotteryProfit = 12,
  MsgID_LotterySync = 13,
  MsgID_SendContactInfo = 14,
  MsgID_LotteryBarrage = 15,
  MsgID_LotteryAward = 16,
  MsgID_SendGift = 17,
  MsgID_SendBarrage = 18,
  MsgID_Light = 19,
  MsgID_ChangeLive = 20,
  MsgID_UpdateVotes = 21,
  MsgID_CloseLive = 22,
  MsgID_KickUser = 23,
  MsgID_ShutUpUser = 24,
  MsgID_StopLive = 25,
  MsgID_ResumeUser = 26,
  MsgID_SetAdmin = 27,
  MsgID_BuyGuard = 28,
  MsgID_SendRed = 29,
  MsgID_RequestFans = 30,
  MsgID_LotteryInfo = 31,
  MsgID_OpenAward = 32,
  MsgID_PlatGame = 33,
  MsgID_TranslateContent = 34,
  MsgID_GiveVideoTicket = 35,
  MsgID_AppTopNotice = 36,
};

GPBEnumDescriptor *MsgID_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MsgID_IsValidValue(int32_t value);

#pragma mark - CommonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface CommonRoot : GPBRootObject
@end

#pragma mark - StreamMsg

typedef GPB_ENUM(StreamMsg_FieldNumber) {
  StreamMsg_FieldNumber_MsgId = 1,
  StreamMsg_FieldNumber_MsgData = 2,
};

GPB_FINAL @interface StreamMsg : GPBMessage

@property(nonatomic, readwrite) MsgID msgId;

@property(nonatomic, readwrite) BOOL hasMsgId;
@property(nonatomic, readwrite, copy, null_resettable) NSData *msgData;
/** Test to see if @c msgData has been set. */
@property(nonatomic, readwrite) BOOL hasMsgData;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
