// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Common.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CommonRoot

@implementation CommonRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - CommonRoot_FileDescriptor

static GPBFileDescriptor *CommonRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"common"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - Enum MsgID

GPBEnumDescriptor *MsgID_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "SystemNot\000SendMsg\000StartEndLive\000LiveConne"
        "ct\000LivePk\000ConnectVideo\000Disconnect\000KyGame"
        "\000LotteryBet\000LotteryOpenAward\000MoneyChange"
        "\000LotteryDividend\000LotteryProfit\000LotterySy"
        "nc\000SendContactInfo\000LotteryBarrage\000Lotter"
        "yAward\000SendGift\000SendBarrage\000Light\000Change"
        "Live\000UpdateVotes\000CloseLive\000KickUser\000Shut"
        "UpUser\000StopLive\000ResumeUser\000SetAdmin\000BuyG"
        "uard\000SendRed\000RequestFans\000LotteryInfo\000Ope"
        "nAward\000PlatGame\000TranslateContent\000GiveVid"
        "eoTicket\000AppTopNotice\000";
    static const int32_t values[] = {
        MsgID_SystemNot,
        MsgID_SendMsg,
        MsgID_StartEndLive,
        MsgID_LiveConnect,
        MsgID_LivePk,
        MsgID_ConnectVideo,
        MsgID_Disconnect,
        MsgID_KyGame,
        MsgID_LotteryBet,
        MsgID_LotteryOpenAward,
        MsgID_MoneyChange,
        MsgID_LotteryDividend,
        MsgID_LotteryProfit,
        MsgID_LotterySync,
        MsgID_SendContactInfo,
        MsgID_LotteryBarrage,
        MsgID_LotteryAward,
        MsgID_SendGift,
        MsgID_SendBarrage,
        MsgID_Light,
        MsgID_ChangeLive,
        MsgID_UpdateVotes,
        MsgID_CloseLive,
        MsgID_KickUser,
        MsgID_ShutUpUser,
        MsgID_StopLive,
        MsgID_ResumeUser,
        MsgID_SetAdmin,
        MsgID_BuyGuard,
        MsgID_SendRed,
        MsgID_RequestFans,
        MsgID_LotteryInfo,
        MsgID_OpenAward,
        MsgID_PlatGame,
        MsgID_TranslateContent,
        MsgID_GiveVideoTicket,
        MsgID_AppTopNotice,
    };
    static const char *extraTextFormatInfo = "%\000\t\000\001\007\000\002\014\000\003\013\000\004\005A\000\005\014\000\006*\000\007&\000\010\n\000\t\020\000\n+\000\013\017\000\014\r\000\r\013\000\016\017\000\017\016\000\020\014\000\021\010\000\022\013\000\023%\000\024*\000\025+\000\026\t\000\027\010\000\030\n\000\031(\000\032\n\000\033(\000\034\010\000\035\007\000\036+\000\037+\000 )\000!(\000\"\020\000#\017\000$\014\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(MsgID)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:MsgID_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL MsgID_IsValidValue(int32_t value__) {
  switch (value__) {
    case MsgID_SystemNot:
    case MsgID_SendMsg:
    case MsgID_StartEndLive:
    case MsgID_LiveConnect:
    case MsgID_LivePk:
    case MsgID_ConnectVideo:
    case MsgID_Disconnect:
    case MsgID_KyGame:
    case MsgID_LotteryBet:
    case MsgID_LotteryOpenAward:
    case MsgID_MoneyChange:
    case MsgID_LotteryDividend:
    case MsgID_LotteryProfit:
    case MsgID_LotterySync:
    case MsgID_SendContactInfo:
    case MsgID_LotteryBarrage:
    case MsgID_LotteryAward:
    case MsgID_SendGift:
    case MsgID_SendBarrage:
    case MsgID_Light:
    case MsgID_ChangeLive:
    case MsgID_UpdateVotes:
    case MsgID_CloseLive:
    case MsgID_KickUser:
    case MsgID_ShutUpUser:
    case MsgID_StopLive:
    case MsgID_ResumeUser:
    case MsgID_SetAdmin:
    case MsgID_BuyGuard:
    case MsgID_SendRed:
    case MsgID_RequestFans:
    case MsgID_LotteryInfo:
    case MsgID_OpenAward:
    case MsgID_PlatGame:
    case MsgID_TranslateContent:
    case MsgID_GiveVideoTicket:
    case MsgID_AppTopNotice:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - StreamMsg

@implementation StreamMsg

@dynamic hasMsgId, msgId;
@dynamic hasMsgData, msgData;

typedef struct StreamMsg__storage_ {
  uint32_t _has_storage_[1];
  MsgID msgId;
  NSData *msgData;
} StreamMsg__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "msgId",
        .dataTypeSpecific.enumDescFunc = MsgID_EnumDescriptor,
        .number = StreamMsg_FieldNumber_MsgId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(StreamMsg__storage_, msgId),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "msgData",
        .dataTypeSpecific.clazz = Nil,
        .number = StreamMsg_FieldNumber_MsgData,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(StreamMsg__storage_, msgData),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[StreamMsg class]
                                     rootClass:[CommonRoot class]
                                          file:CommonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(StreamMsg__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\004A\000\002\007\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
