// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s2c.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AppTopNotice_Msg;
@class BuyGuard_Msg;
@class GiveVideoTicket_Msg;
@class KickUser_Msg;
@class LiveConnect_Msg;
@class LivePK_Msg;
@class LotteryAward_Msg;
@class LotteryBarrage_Barrage;
@class LotteryBarrage_CTStruct;
@class LotteryBarrage_Msg;
@class LotteryBet_CTStruct;
@class LotteryBet_Msg;
@class LotteryDividend_CTStruct;
@class LotteryDividend_Msg;
@class LotteryOpenAward_BaiJiaLeStruct;
@class LotteryOpenAward_LongHuStruct;
@class LotteryOpenAward_Msg;
@class LotteryOpenAward_NiuStruct;
@class LotteryOpenAward_ZhaJinHuaStruct;
@class LotteryProfit_CTStruct;
@class LotteryProfit_Msg;
@class LotterySync_LotteryInfo;
@class LotterySync_Msg;
@class MoneyChange_Msg;
@class SendBarrage_CTStruct;
@class SendBarrage_Msg;
@class SendContactInfo_Msg;
@class SendGift_GiftInfo;
@class SendGift_Msg;
@class SendMsg_CTStruct;
@class SendMsg_Msg;
@class SendRed_Msg;
@class ShutUpUser_Msg;
@class StartEndLive_Msg;
@class SystemNot_Msg;
@class TranslateContent_Msg;
@class changeLive_Msg;
@class disconnect_CTStruct;
@class disconnect_Msg;
@class kyGame_Msg;
@class light_Msg;
@class platGame_Msg;
@class requestFans_Fans;
@class requestFans_InfoStruct;
@class requestFans_Msg;
@class requestFans_UserInfo;
@class setAdmin_Msg;
@class stopLive_Msg;
@class updateVotes_Msg;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - S2CRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface S2CRoot : GPBRootObject
@end

#pragma mark - SystemNot

typedef GPB_ENUM(SystemNot_FieldNumber) {
  SystemNot_FieldNumber_Retcode = 1,
  SystemNot_FieldNumber_Retmsg = 2,
  SystemNot_FieldNumber_Msg = 3,
};

GPB_FINAL @interface SystemNot : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) SystemNot_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - SystemNot_Msg

typedef GPB_ENUM(SystemNot_Msg_FieldNumber) {
  SystemNot_Msg_FieldNumber_Action = 1,
  SystemNot_Msg_FieldNumber_Ct = 2,
  SystemNot_Msg_FieldNumber_Uname = 3,
  SystemNot_Msg_FieldNumber_Msgtype = 4,
};

GPB_FINAL @interface SystemNot_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@end

#pragma mark - LiveConnect

typedef GPB_ENUM(LiveConnect_FieldNumber) {
  LiveConnect_FieldNumber_Retcode = 1,
  LiveConnect_FieldNumber_Retmsg = 2,
  LiveConnect_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LiveConnect : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LiveConnect_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LiveConnect_Msg

typedef GPB_ENUM(LiveConnect_Msg_FieldNumber) {
  LiveConnect_Msg_FieldNumber_Action = 1,
  LiveConnect_Msg_FieldNumber_Msgtype = 2,
  LiveConnect_Msg_FieldNumber_Pkuid = 3,
  LiveConnect_Msg_FieldNumber_Pkpull = 4,
  LiveConnect_Msg_FieldNumber_Uid = 5,
  LiveConnect_Msg_FieldNumber_Uname = 6,
};

GPB_FINAL @interface LiveConnect_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t pkuid;

@property(nonatomic, readwrite) BOOL hasPkuid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *pkpull;
/** Test to see if @c pkpull has been set. */
@property(nonatomic, readwrite) BOOL hasPkpull;

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@end

#pragma mark - LivePK

typedef GPB_ENUM(LivePK_FieldNumber) {
  LivePK_FieldNumber_Retcode = 1,
  LivePK_FieldNumber_Retmsg = 2,
  LivePK_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LivePK : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LivePK_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LivePK_Msg

typedef GPB_ENUM(LivePK_Msg_FieldNumber) {
  LivePK_Msg_FieldNumber_Action = 1,
  LivePK_Msg_FieldNumber_Msgtype = 2,
  LivePK_Msg_FieldNumber_Pkuid = 3,
  LivePK_Msg_FieldNumber_Uid = 4,
  LivePK_Msg_FieldNumber_Uname = 5,
};

GPB_FINAL @interface LivePK_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t pkuid;

@property(nonatomic, readwrite) BOOL hasPkuid;
@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@end

#pragma mark - requestFans

typedef GPB_ENUM(requestFans_FieldNumber) {
  requestFans_FieldNumber_Retcode = 1,
  requestFans_FieldNumber_Retmsg = 2,
  requestFans_FieldNumber_Msg = 3,
};

GPB_FINAL @interface requestFans : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) requestFans_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - requestFans_UserInfo

typedef GPB_ENUM(requestFans_UserInfo_FieldNumber) {
  requestFans_UserInfo_FieldNumber_Id_p = 1,
  requestFans_UserInfo_FieldNumber_Avatar = 2,
  requestFans_UserInfo_FieldNumber_GuardType = 3,
  requestFans_UserInfo_FieldNumber_Level = 4,
};

GPB_FINAL @interface requestFans_UserInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;
/** Test to see if @c avatar has been set. */
@property(nonatomic, readwrite) BOOL hasAvatar;

@property(nonatomic, readwrite) uint32_t guardType;

@property(nonatomic, readwrite) BOOL hasGuardType;
@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) BOOL hasLevel;
@end

#pragma mark - requestFans_InfoStruct

typedef GPB_ENUM(requestFans_InfoStruct_FieldNumber) {
  requestFans_InfoStruct_FieldNumber_ListArray = 1,
};

GPB_FINAL @interface requestFans_InfoStruct : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<requestFans_UserInfo*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - requestFans_Fans

typedef GPB_ENUM(requestFans_Fans_FieldNumber) {
  requestFans_Fans_FieldNumber_Code = 1,
  requestFans_Fans_FieldNumber_Info = 2,
  requestFans_Fans_FieldNumber_Msg = 3,
};

GPB_FINAL @interface requestFans_Fans : GPBMessage

@property(nonatomic, readwrite) uint32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
@property(nonatomic, readwrite, strong, null_resettable) requestFans_InfoStruct *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - requestFans_Msg

typedef GPB_ENUM(requestFans_Msg_FieldNumber) {
  requestFans_Msg_FieldNumber_Action = 1,
  requestFans_Msg_FieldNumber_Msgtype = 2,
  requestFans_Msg_FieldNumber_Ct = 3,
};

GPB_FINAL @interface requestFans_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, strong, null_resettable) requestFans_Fans *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@end

#pragma mark - SendMsg

typedef GPB_ENUM(SendMsg_FieldNumber) {
  SendMsg_FieldNumber_Retcode = 1,
  SendMsg_FieldNumber_Retmsg = 2,
  SendMsg_FieldNumber_Msg = 3,
};

GPB_FINAL @interface SendMsg : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) SendMsg_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - SendMsg_CTStruct

typedef GPB_ENUM(SendMsg_CTStruct_FieldNumber) {
  SendMsg_CTStruct_FieldNumber_Id_p = 1,
  SendMsg_CTStruct_FieldNumber_UserNicename = 2,
  SendMsg_CTStruct_FieldNumber_Avatar = 3,
  SendMsg_CTStruct_FieldNumber_AvatarThumb = 4,
  SendMsg_CTStruct_FieldNumber_Level = 5,
  SendMsg_CTStruct_FieldNumber_Usertype = 6,
  SendMsg_CTStruct_FieldNumber_VipType = 7,
  SendMsg_CTStruct_FieldNumber_GuardType = 8,
  SendMsg_CTStruct_FieldNumber_Liangname = 9,
  SendMsg_CTStruct_FieldNumber_CarId = 10,
  SendMsg_CTStruct_FieldNumber_CarSwf = 11,
  SendMsg_CTStruct_FieldNumber_CarSwftime = 12,
  SendMsg_CTStruct_FieldNumber_CarWords = 13,
  SendMsg_CTStruct_FieldNumber_IsAnchor = 14,
  SendMsg_CTStruct_FieldNumber_Heart = 15,
  SendMsg_CTStruct_FieldNumber_KingIcon = 16,
};

GPB_FINAL @interface SendMsg_CTStruct : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userNicename;
/** Test to see if @c userNicename has been set. */
@property(nonatomic, readwrite) BOOL hasUserNicename;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;
/** Test to see if @c avatar has been set. */
@property(nonatomic, readwrite) BOOL hasAvatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarThumb;
/** Test to see if @c avatarThumb has been set. */
@property(nonatomic, readwrite) BOOL hasAvatarThumb;

@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) BOOL hasLevel;
@property(nonatomic, readwrite) uint32_t usertype;

@property(nonatomic, readwrite) BOOL hasUsertype;
@property(nonatomic, readwrite) uint32_t vipType;

@property(nonatomic, readwrite) BOOL hasVipType;
@property(nonatomic, readwrite) uint32_t guardType;

@property(nonatomic, readwrite) BOOL hasGuardType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *liangname;
/** Test to see if @c liangname has been set. */
@property(nonatomic, readwrite) BOOL hasLiangname;

@property(nonatomic, readwrite) uint32_t carId;

@property(nonatomic, readwrite) BOOL hasCarId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *carSwf;
/** Test to see if @c carSwf has been set. */
@property(nonatomic, readwrite) BOOL hasCarSwf;

@property(nonatomic, readwrite, copy, null_resettable) NSString *carSwftime;
/** Test to see if @c carSwftime has been set. */
@property(nonatomic, readwrite) BOOL hasCarSwftime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *carWords;
/** Test to see if @c carWords has been set. */
@property(nonatomic, readwrite) BOOL hasCarWords;

@property(nonatomic, readwrite) BOOL isAnchor;

@property(nonatomic, readwrite) BOOL hasIsAnchor;
@property(nonatomic, readwrite, copy, null_resettable) NSString *heart;
/** Test to see if @c heart has been set. */
@property(nonatomic, readwrite) BOOL hasHeart;

@property(nonatomic, readwrite, copy, null_resettable) NSString *kingIcon;
/** Test to see if @c kingIcon has been set. */
@property(nonatomic, readwrite) BOOL hasKingIcon;

@end

#pragma mark - SendMsg_Msg

typedef GPB_ENUM(SendMsg_Msg_FieldNumber) {
  SendMsg_Msg_FieldNumber_Action = 1,
  SendMsg_Msg_FieldNumber_Ct = 2,
  SendMsg_Msg_FieldNumber_Msgtype = 3,
  SendMsg_Msg_FieldNumber_Content = 4,
  SendMsg_Msg_FieldNumber_Uname = 5,
  SendMsg_Msg_FieldNumber_Lang = 6,
};

GPB_FINAL @interface SendMsg_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, strong, null_resettable) SendMsg_CTStruct *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lang;
/** Test to see if @c lang has been set. */
@property(nonatomic, readwrite) BOOL hasLang;

@end

#pragma mark - StartEndLive

typedef GPB_ENUM(StartEndLive_FieldNumber) {
  StartEndLive_FieldNumber_Retcode = 1,
  StartEndLive_FieldNumber_Retmsg = 2,
  StartEndLive_FieldNumber_Msg = 3,
};

GPB_FINAL @interface StartEndLive : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) StartEndLive_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - StartEndLive_Msg

typedef GPB_ENUM(StartEndLive_Msg_FieldNumber) {
  StartEndLive_Msg_FieldNumber_Action = 1,
  StartEndLive_Msg_FieldNumber_Ct = 2,
  StartEndLive_Msg_FieldNumber_Uname = 3,
  StartEndLive_Msg_FieldNumber_Msgtype = 4,
};

GPB_FINAL @interface StartEndLive_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@end

#pragma mark - disconnect

typedef GPB_ENUM(disconnect_FieldNumber) {
  disconnect_FieldNumber_Retcode = 1,
  disconnect_FieldNumber_Retmsg = 2,
  disconnect_FieldNumber_Msg = 3,
};

GPB_FINAL @interface disconnect : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) disconnect_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - disconnect_CTStruct

typedef GPB_ENUM(disconnect_CTStruct_FieldNumber) {
  disconnect_CTStruct_FieldNumber_Id_p = 1,
  disconnect_CTStruct_FieldNumber_UserNicename = 2,
  disconnect_CTStruct_FieldNumber_Avatar = 3,
  disconnect_CTStruct_FieldNumber_Level = 4,
};

GPB_FINAL @interface disconnect_CTStruct : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userNicename;
/** Test to see if @c userNicename has been set. */
@property(nonatomic, readwrite) BOOL hasUserNicename;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;
/** Test to see if @c avatar has been set. */
@property(nonatomic, readwrite) BOOL hasAvatar;

@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) BOOL hasLevel;
@end

#pragma mark - disconnect_Msg

typedef GPB_ENUM(disconnect_Msg_FieldNumber) {
  disconnect_Msg_FieldNumber_Action = 1,
  disconnect_Msg_FieldNumber_Ct = 2,
  disconnect_Msg_FieldNumber_Uid = 3,
  disconnect_Msg_FieldNumber_Uname = 4,
  disconnect_Msg_FieldNumber_Msgtype = 5,
};

GPB_FINAL @interface disconnect_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, strong, null_resettable) disconnect_CTStruct *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@end

#pragma mark - kyGame

typedef GPB_ENUM(kyGame_FieldNumber) {
  kyGame_FieldNumber_Retcode = 1,
  kyGame_FieldNumber_Retmsg = 2,
  kyGame_FieldNumber_Msg = 3,
};

GPB_FINAL @interface kyGame : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) kyGame_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - kyGame_Msg

typedef GPB_ENUM(kyGame_Msg_FieldNumber) {
  kyGame_Msg_FieldNumber_Action = 1,
  kyGame_Msg_FieldNumber_Ct = 2,
  kyGame_Msg_FieldNumber_Msgtype = 3,
  kyGame_Msg_FieldNumber_GamePlat = 4,
  kyGame_Msg_FieldNumber_GameKindId = 5,
};

GPB_FINAL @interface kyGame_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *gamePlat;
/** Test to see if @c gamePlat has been set. */
@property(nonatomic, readwrite) BOOL hasGamePlat;

@property(nonatomic, readwrite) uint32_t gameKindId;

@property(nonatomic, readwrite) BOOL hasGameKindId;
@end

#pragma mark - platGame

typedef GPB_ENUM(platGame_FieldNumber) {
  platGame_FieldNumber_Retcode = 1,
  platGame_FieldNumber_Retmsg = 2,
  platGame_FieldNumber_Msg = 3,
};

GPB_FINAL @interface platGame : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) platGame_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - platGame_Msg

typedef GPB_ENUM(platGame_Msg_FieldNumber) {
  platGame_Msg_FieldNumber_Action = 1,
  platGame_Msg_FieldNumber_Ct = 2,
  platGame_Msg_FieldNumber_Msgtype = 3,
  platGame_Msg_FieldNumber_GamePlat = 4,
  platGame_Msg_FieldNumber_GameKindId = 5,
  platGame_Msg_FieldNumber_Ext1 = 6,
};

GPB_FINAL @interface platGame_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *gamePlat;
/** Test to see if @c gamePlat has been set. */
@property(nonatomic, readwrite) BOOL hasGamePlat;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameKindId;
/** Test to see if @c gameKindId has been set. */
@property(nonatomic, readwrite) BOOL hasGameKindId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ext1;
/** Test to see if @c ext1 has been set. */
@property(nonatomic, readwrite) BOOL hasExt1;

@end

#pragma mark - TranslateContent

typedef GPB_ENUM(TranslateContent_FieldNumber) {
  TranslateContent_FieldNumber_Retcode = 1,
  TranslateContent_FieldNumber_Retmsg = 2,
  TranslateContent_FieldNumber_Msg = 3,
};

GPB_FINAL @interface TranslateContent : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) TranslateContent_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - TranslateContent_Msg

typedef GPB_ENUM(TranslateContent_Msg_FieldNumber) {
  TranslateContent_Msg_FieldNumber_Action = 1,
  TranslateContent_Msg_FieldNumber_Ct = 2,
  TranslateContent_Msg_FieldNumber_Msgtype = 3,
  TranslateContent_Msg_FieldNumber_Content = 4,
};

GPB_FINAL @interface TranslateContent_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

#pragma mark - GiveVideoTicket

typedef GPB_ENUM(GiveVideoTicket_FieldNumber) {
  GiveVideoTicket_FieldNumber_Retcode = 1,
  GiveVideoTicket_FieldNumber_Retmsg = 2,
  GiveVideoTicket_FieldNumber_Msg = 3,
};

GPB_FINAL @interface GiveVideoTicket : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) GiveVideoTicket_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - GiveVideoTicket_Msg

typedef GPB_ENUM(GiveVideoTicket_Msg_FieldNumber) {
  GiveVideoTicket_Msg_FieldNumber_Action = 1,
  GiveVideoTicket_Msg_FieldNumber_Ct = 2,
  GiveVideoTicket_Msg_FieldNumber_Msgtype = 3,
  GiveVideoTicket_Msg_FieldNumber_TicketNum = 4,
};

GPB_FINAL @interface GiveVideoTicket_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t ticketNum;

@property(nonatomic, readwrite) BOOL hasTicketNum;
@end

#pragma mark - LotteryAward

typedef GPB_ENUM(LotteryAward_FieldNumber) {
  LotteryAward_FieldNumber_Retcode = 1,
  LotteryAward_FieldNumber_Retmsg = 2,
  LotteryAward_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LotteryAward : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LotteryAward_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LotteryAward_Msg

typedef GPB_ENUM(LotteryAward_Msg_FieldNumber) {
  LotteryAward_Msg_FieldNumber_Action = 1,
  LotteryAward_Msg_FieldNumber_AwardMoney = 2,
  LotteryAward_Msg_FieldNumber_Msgtype = 3,
};

GPB_FINAL @interface LotteryAward_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) float awardMoney;

@property(nonatomic, readwrite) BOOL hasAwardMoney;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@end

#pragma mark - LotteryBarrage

typedef GPB_ENUM(LotteryBarrage_FieldNumber) {
  LotteryBarrage_FieldNumber_Retcode = 1,
  LotteryBarrage_FieldNumber_Retmsg = 2,
  LotteryBarrage_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LotteryBarrage : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LotteryBarrage_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LotteryBarrage_CTStruct

typedef GPB_ENUM(LotteryBarrage_CTStruct_FieldNumber) {
  LotteryBarrage_CTStruct_FieldNumber_Nickname = 1,
  LotteryBarrage_CTStruct_FieldNumber_LotteryName = 2,
  LotteryBarrage_CTStruct_FieldNumber_Way = 3,
  LotteryBarrage_CTStruct_FieldNumber_Totalmoney = 4,
  LotteryBarrage_CTStruct_FieldNumber_ShowType = 5,
};

GPB_FINAL @interface LotteryBarrage_CTStruct : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lotteryName;
/** Test to see if @c lotteryName has been set. */
@property(nonatomic, readwrite) BOOL hasLotteryName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *way;
/** Test to see if @c way has been set. */
@property(nonatomic, readwrite) BOOL hasWay;

@property(nonatomic, readwrite, copy, null_resettable) NSString *totalmoney;
/** Test to see if @c totalmoney has been set. */
@property(nonatomic, readwrite) BOOL hasTotalmoney;

@property(nonatomic, readwrite) uint32_t showType;

@property(nonatomic, readwrite) BOOL hasShowType;
@end

#pragma mark - LotteryBarrage_Barrage

typedef GPB_ENUM(LotteryBarrage_Barrage_FieldNumber) {
  LotteryBarrage_Barrage_FieldNumber_Ct = 1,
  LotteryBarrage_Barrage_FieldNumber_Lt = 2,
  LotteryBarrage_Barrage_FieldNumber_Lid = 3,
  LotteryBarrage_Barrage_FieldNumber_St = 4,
};

GPB_FINAL @interface LotteryBarrage_Barrage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) LotteryBarrage_CTStruct *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t lt;

@property(nonatomic, readwrite) BOOL hasLt;
@property(nonatomic, readwrite) uint32_t lid;

@property(nonatomic, readwrite) BOOL hasLid;
@property(nonatomic, readwrite) uint32_t st;

@property(nonatomic, readwrite) BOOL hasSt;
@end

#pragma mark - LotteryBarrage_Msg

typedef GPB_ENUM(LotteryBarrage_Msg_FieldNumber) {
  LotteryBarrage_Msg_FieldNumber_Action = 1,
  LotteryBarrage_Msg_FieldNumber_BarrageArrArray = 2,
  LotteryBarrage_Msg_FieldNumber_Msgtype = 3,
};

GPB_FINAL @interface LotteryBarrage_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LotteryBarrage_Barrage*> *barrageArrArray;
/** The number of items in @c barrageArrArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger barrageArrArray_Count;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@end

#pragma mark - LotteryBet

typedef GPB_ENUM(LotteryBet_FieldNumber) {
  LotteryBet_FieldNumber_Retcode = 1,
  LotteryBet_FieldNumber_Retmsg = 2,
  LotteryBet_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LotteryBet : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LotteryBet_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LotteryBet_CTStruct

typedef GPB_ENUM(LotteryBet_CTStruct_FieldNumber) {
  LotteryBet_CTStruct_FieldNumber_Nickname = 1,
  LotteryBet_CTStruct_FieldNumber_LotteryName = 2,
  LotteryBet_CTStruct_FieldNumber_Totalmoney = 3,
};

GPB_FINAL @interface LotteryBet_CTStruct : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lotteryName;
/** Test to see if @c lotteryName has been set. */
@property(nonatomic, readwrite) BOOL hasLotteryName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *totalmoney;
/** Test to see if @c totalmoney has been set. */
@property(nonatomic, readwrite) BOOL hasTotalmoney;

@end

#pragma mark - LotteryBet_Msg

typedef GPB_ENUM(LotteryBet_Msg_FieldNumber) {
  LotteryBet_Msg_FieldNumber_Action = 1,
  LotteryBet_Msg_FieldNumber_Ct = 2,
  LotteryBet_Msg_FieldNumber_Msgtype = 3,
  LotteryBet_Msg_FieldNumber_LotteryType = 4,
  LotteryBet_Msg_FieldNumber_OptionName = 5,
  LotteryBet_Msg_FieldNumber_Way = 6,
  LotteryBet_Msg_FieldNumber_Money = 7,
  LotteryBet_Msg_FieldNumber_Issue = 8,
  LotteryBet_Msg_FieldNumber_OptionNameSt = 9,
  LotteryBet_Msg_FieldNumber_WaySt = 10,
  LotteryBet_Msg_FieldNumber_Uid = 11,
  LotteryBet_Msg_FieldNumber_ChatSelfShow = 12,
};

GPB_FINAL @interface LotteryBet_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, strong, null_resettable) LotteryBet_CTStruct *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t lotteryType;

@property(nonatomic, readwrite) BOOL hasLotteryType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *optionName;
/** Test to see if @c optionName has been set. */
@property(nonatomic, readwrite) BOOL hasOptionName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *way;
/** Test to see if @c way has been set. */
@property(nonatomic, readwrite) BOOL hasWay;

@property(nonatomic, readwrite, copy, null_resettable) NSString *money;
/** Test to see if @c money has been set. */
@property(nonatomic, readwrite) BOOL hasMoney;

@property(nonatomic, readwrite) uint64_t issue;

@property(nonatomic, readwrite) BOOL hasIssue;
@property(nonatomic, readwrite, copy, null_resettable) NSString *optionNameSt;
/** Test to see if @c optionNameSt has been set. */
@property(nonatomic, readwrite) BOOL hasOptionNameSt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *waySt;
/** Test to see if @c waySt has been set. */
@property(nonatomic, readwrite) BOOL hasWaySt;

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite) BOOL chatSelfShow;

@property(nonatomic, readwrite) BOOL hasChatSelfShow;
@end

#pragma mark - LotteryOpenAward

typedef GPB_ENUM(LotteryOpenAward_FieldNumber) {
  LotteryOpenAward_FieldNumber_Retcode = 1,
  LotteryOpenAward_FieldNumber_Retmsg = 2,
  LotteryOpenAward_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LotteryOpenAward : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LotteryOpenAward_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LotteryOpenAward_NiuStruct

typedef GPB_ENUM(LotteryOpenAward_NiuStruct_FieldNumber) {
  LotteryOpenAward_NiuStruct_FieldNumber_RedNiu = 1,
  LotteryOpenAward_NiuStruct_FieldNumber_BlueNiu = 2,
};

GPB_FINAL @interface LotteryOpenAward_NiuStruct : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *redNiu;
/** Test to see if @c redNiu has been set. */
@property(nonatomic, readwrite) BOOL hasRedNiu;

@property(nonatomic, readwrite, copy, null_resettable) NSString *blueNiu;
/** Test to see if @c blueNiu has been set. */
@property(nonatomic, readwrite) BOOL hasBlueNiu;

@end

#pragma mark - LotteryOpenAward_BaiJiaLeStruct

typedef GPB_ENUM(LotteryOpenAward_BaiJiaLeStruct_FieldNumber) {
  LotteryOpenAward_BaiJiaLeStruct_FieldNumber_ZhuangDian = 1,
  LotteryOpenAward_BaiJiaLeStruct_FieldNumber_XianDian = 2,
  LotteryOpenAward_BaiJiaLeStruct_FieldNumber_ZhuangDianStr = 3,
  LotteryOpenAward_BaiJiaLeStruct_FieldNumber_XianDianStr = 4,
  LotteryOpenAward_BaiJiaLeStruct_FieldNumber_WhoWin = 5,
  LotteryOpenAward_BaiJiaLeStruct_FieldNumber_ZhuangxianStr = 6,
};

GPB_FINAL @interface LotteryOpenAward_BaiJiaLeStruct : GPBMessage

/** 如:1 */
@property(nonatomic, readwrite) uint32_t zhuangDian;

@property(nonatomic, readwrite) BOOL hasZhuangDian;
/** 如:1 */
@property(nonatomic, readwrite) uint32_t xianDian;

@property(nonatomic, readwrite) BOOL hasXianDian;
/** 如:1点 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *zhuangDianStr;
/** Test to see if @c zhuangDianStr has been set. */
@property(nonatomic, readwrite) BOOL hasZhuangDianStr;

/** 如:1点 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *xianDianStr;
/** Test to see if @c xianDianStr has been set. */
@property(nonatomic, readwrite) BOOL hasXianDianStr;

/** 0:庄胜 1:闲胜 2:和 */
@property(nonatomic, readwrite) uint32_t whoWin;

@property(nonatomic, readwrite) BOOL hasWhoWin;
/** 庄家1点 vs 闲家2点 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *zhuangxianStr;
/** Test to see if @c zhuangxianStr has been set. */
@property(nonatomic, readwrite) BOOL hasZhuangxianStr;

@end

#pragma mark - LotteryOpenAward_ZhaJinHuaStruct

typedef GPB_ENUM(LotteryOpenAward_ZhaJinHuaStruct_FieldNumber) {
  LotteryOpenAward_ZhaJinHuaStruct_FieldNumber_WhoWin = 1,
  LotteryOpenAward_ZhaJinHuaStruct_FieldNumber_PaiTypeArray = 2,
  LotteryOpenAward_ZhaJinHuaStruct_FieldNumber_PaiTypeStrArray = 3,
};

GPB_FINAL @interface LotteryOpenAward_ZhaJinHuaStruct : GPBMessage

/** 0:玩家一 1:玩家二 2:玩家三 */
@property(nonatomic, readwrite) uint32_t whoWin;

@property(nonatomic, readwrite) BOOL hasWhoWin;
/** 1:高牌 2:对子 3:顺子 4:同花 5:同花顺 6:三条 */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *paiTypeArray;
/** The number of items in @c paiTypeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger paiTypeArray_Count;

/** (多语言文本)高牌 对子 顺子 同花 同花顺 三条 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *paiTypeStrArray;
/** The number of items in @c paiTypeStrArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger paiTypeStrArray_Count;

@end

#pragma mark - LotteryOpenAward_LongHuStruct

typedef GPB_ENUM(LotteryOpenAward_LongHuStruct_FieldNumber) {
  LotteryOpenAward_LongHuStruct_FieldNumber_WhoWin = 1,
  LotteryOpenAward_LongHuStruct_FieldNumber_DragonDian = 2,
  LotteryOpenAward_LongHuStruct_FieldNumber_DragonDianStr = 3,
  LotteryOpenAward_LongHuStruct_FieldNumber_TigerDian = 4,
  LotteryOpenAward_LongHuStruct_FieldNumber_TigerDianStr = 5,
  LotteryOpenAward_LongHuStruct_FieldNumber_DragonTigerStr = 6,
};

GPB_FINAL @interface LotteryOpenAward_LongHuStruct : GPBMessage

/** 0:龙 1:虎 2:和 */
@property(nonatomic, readwrite) uint32_t whoWin;

@property(nonatomic, readwrite) BOOL hasWhoWin;
/** 如:1 */
@property(nonatomic, readwrite) uint32_t dragonDian;

@property(nonatomic, readwrite) BOOL hasDragonDian;
/** 如:1点 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *dragonDianStr;
/** Test to see if @c dragonDianStr has been set. */
@property(nonatomic, readwrite) BOOL hasDragonDianStr;

/** 如:1 */
@property(nonatomic, readwrite) uint32_t tigerDian;

@property(nonatomic, readwrite) BOOL hasTigerDian;
/** 如:1点 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tigerDianStr;
/** Test to see if @c tigerDianStr has been set. */
@property(nonatomic, readwrite) BOOL hasTigerDianStr;

/** 龙:{0} vs 虎:{1} */
@property(nonatomic, readwrite, copy, null_resettable) NSString *dragonTigerStr;
/** Test to see if @c dragonTigerStr has been set. */
@property(nonatomic, readwrite) BOOL hasDragonTigerStr;

@end

#pragma mark - LotteryOpenAward_Msg

typedef GPB_ENUM(LotteryOpenAward_Msg_FieldNumber) {
  LotteryOpenAward_Msg_FieldNumber_Action = 1,
  LotteryOpenAward_Msg_FieldNumber_Ct = 2,
  LotteryOpenAward_Msg_FieldNumber_Msgtype = 3,
  LotteryOpenAward_Msg_FieldNumber_LotteryType = 4,
  LotteryOpenAward_Msg_FieldNumber_Result = 5,
  LotteryOpenAward_Msg_FieldNumber_Name = 6,
  LotteryOpenAward_Msg_FieldNumber_Issue = 7,
  LotteryOpenAward_Msg_FieldNumber_SumResultStr = 8,
  LotteryOpenAward_Msg_FieldNumber_Niu = 9,
  LotteryOpenAward_Msg_FieldNumber_WinWaysArray = 10,
  LotteryOpenAward_Msg_FieldNumber_Bjl = 11,
  LotteryOpenAward_Msg_FieldNumber_Zjh = 12,
  LotteryOpenAward_Msg_FieldNumber_Lh = 13,
};

GPB_FINAL @interface LotteryOpenAward_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t lotteryType;

@property(nonatomic, readwrite) BOOL hasLotteryType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite) uint64_t issue;

@property(nonatomic, readwrite) BOOL hasIssue;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sumResultStr;
/** Test to see if @c sumResultStr has been set. */
@property(nonatomic, readwrite) BOOL hasSumResultStr;

@property(nonatomic, readwrite, strong, null_resettable) LotteryOpenAward_NiuStruct *niu;
/** Test to see if @c niu has been set. */
@property(nonatomic, readwrite) BOOL hasNiu;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *winWaysArray;
/** The number of items in @c winWaysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger winWaysArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) LotteryOpenAward_BaiJiaLeStruct *bjl;
/** Test to see if @c bjl has been set. */
@property(nonatomic, readwrite) BOOL hasBjl;

@property(nonatomic, readwrite, strong, null_resettable) LotteryOpenAward_ZhaJinHuaStruct *zjh;
/** Test to see if @c zjh has been set. */
@property(nonatomic, readwrite) BOOL hasZjh;

@property(nonatomic, readwrite, strong, null_resettable) LotteryOpenAward_LongHuStruct *lh;
/** Test to see if @c lh has been set. */
@property(nonatomic, readwrite) BOOL hasLh;

@end

#pragma mark - LotteryDividend

typedef GPB_ENUM(LotteryDividend_FieldNumber) {
  LotteryDividend_FieldNumber_Retcode = 1,
  LotteryDividend_FieldNumber_Retmsg = 2,
  LotteryDividend_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LotteryDividend : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LotteryDividend_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LotteryDividend_CTStruct

typedef GPB_ENUM(LotteryDividend_CTStruct_FieldNumber) {
  LotteryDividend_CTStruct_FieldNumber_Nickname = 1,
  LotteryDividend_CTStruct_FieldNumber_LotteryName = 2,
  LotteryDividend_CTStruct_FieldNumber_Totalmoney = 3,
  LotteryDividend_CTStruct_FieldNumber_FromName = 4,
};

GPB_FINAL @interface LotteryDividend_CTStruct : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lotteryName;
/** Test to see if @c lotteryName has been set. */
@property(nonatomic, readwrite) BOOL hasLotteryName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *totalmoney;
/** Test to see if @c totalmoney has been set. */
@property(nonatomic, readwrite) BOOL hasTotalmoney;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromName;
/** Test to see if @c fromName has been set. */
@property(nonatomic, readwrite) BOOL hasFromName;

@end

#pragma mark - LotteryDividend_Msg

typedef GPB_ENUM(LotteryDividend_Msg_FieldNumber) {
  LotteryDividend_Msg_FieldNumber_Action = 1,
  LotteryDividend_Msg_FieldNumber_Ct = 2,
  LotteryDividend_Msg_FieldNumber_Msgtype = 3,
  LotteryDividend_Msg_FieldNumber_FromUid = 4,
  LotteryDividend_Msg_FieldNumber_FromName = 5,
};

GPB_FINAL @interface LotteryDividend_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, strong, null_resettable) LotteryDividend_CTStruct *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t fromUid;

@property(nonatomic, readwrite) BOOL hasFromUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromName;
/** Test to see if @c fromName has been set. */
@property(nonatomic, readwrite) BOOL hasFromName;

@end

#pragma mark - MoneyChange

typedef GPB_ENUM(MoneyChange_FieldNumber) {
  MoneyChange_FieldNumber_Retcode = 1,
  MoneyChange_FieldNumber_Retmsg = 2,
  MoneyChange_FieldNumber_Msg = 3,
};

GPB_FINAL @interface MoneyChange : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) MoneyChange_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - MoneyChange_Msg

typedef GPB_ENUM(MoneyChange_Msg_FieldNumber) {
  MoneyChange_Msg_FieldNumber_Action = 1,
  MoneyChange_Msg_FieldNumber_Ct = 2,
  MoneyChange_Msg_FieldNumber_Msgtype = 3,
  MoneyChange_Msg_FieldNumber_Issue = 4,
  MoneyChange_Msg_FieldNumber_Money = 5,
};

GPB_FINAL @interface MoneyChange_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint64_t issue;

@property(nonatomic, readwrite) BOOL hasIssue;
@property(nonatomic, readwrite) float money;

@property(nonatomic, readwrite) BOOL hasMoney;
@end

#pragma mark - LotteryProfit

typedef GPB_ENUM(LotteryProfit_FieldNumber) {
  LotteryProfit_FieldNumber_Retcode = 1,
  LotteryProfit_FieldNumber_Retmsg = 2,
  LotteryProfit_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LotteryProfit : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LotteryProfit_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LotteryProfit_CTStruct

typedef GPB_ENUM(LotteryProfit_CTStruct_FieldNumber) {
  LotteryProfit_CTStruct_FieldNumber_Nickname = 1,
  LotteryProfit_CTStruct_FieldNumber_LotteryName = 2,
};

GPB_FINAL @interface LotteryProfit_CTStruct : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lotteryName;
/** Test to see if @c lotteryName has been set. */
@property(nonatomic, readwrite) BOOL hasLotteryName;

@end

#pragma mark - LotteryProfit_Msg

typedef GPB_ENUM(LotteryProfit_Msg_FieldNumber) {
  LotteryProfit_Msg_FieldNumber_Action = 1,
  LotteryProfit_Msg_FieldNumber_Ct = 2,
  LotteryProfit_Msg_FieldNumber_Msgtype = 3,
  LotteryProfit_Msg_FieldNumber_Uid = 4,
  LotteryProfit_Msg_FieldNumber_WinWay = 5,
  LotteryProfit_Msg_FieldNumber_Profit = 6,
};

GPB_FINAL @interface LotteryProfit_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, strong, null_resettable) LotteryProfit_CTStruct *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *winWay;
/** Test to see if @c winWay has been set. */
@property(nonatomic, readwrite) BOOL hasWinWay;

@property(nonatomic, readwrite) uint32_t profit;

@property(nonatomic, readwrite) BOOL hasProfit;
@end

#pragma mark - LotterySync

typedef GPB_ENUM(LotterySync_FieldNumber) {
  LotterySync_FieldNumber_Retcode = 1,
  LotterySync_FieldNumber_Retmsg = 2,
  LotterySync_FieldNumber_Msg = 3,
};

GPB_FINAL @interface LotterySync : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) LotterySync_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - LotterySync_LotteryInfo

typedef GPB_ENUM(LotterySync_LotteryInfo_FieldNumber) {
  LotterySync_LotteryInfo_FieldNumber_Name = 1,
  LotterySync_LotteryInfo_FieldNumber_Logo = 2,
  LotterySync_LotteryInfo_FieldNumber_Time = 3,
  LotterySync_LotteryInfo_FieldNumber_SealingTim = 4,
  LotterySync_LotteryInfo_FieldNumber_Issue = 5,
  LotterySync_LotteryInfo_FieldNumber_StopOrSell = 6,
  LotterySync_LotteryInfo_FieldNumber_StopMsg = 7,
  LotterySync_LotteryInfo_FieldNumber_LotteryType = 8,
  LotterySync_LotteryInfo_FieldNumber_SerTime = 9,
};

GPB_FINAL @interface LotterySync_LotteryInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *logo;
/** Test to see if @c logo has been set. */
@property(nonatomic, readwrite) BOOL hasLogo;

@property(nonatomic, readwrite) uint32_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite) uint32_t sealingTim;

@property(nonatomic, readwrite) BOOL hasSealingTim;
@property(nonatomic, readwrite) uint64_t issue;

@property(nonatomic, readwrite) BOOL hasIssue;
@property(nonatomic, readwrite) uint32_t stopOrSell;

@property(nonatomic, readwrite) BOOL hasStopOrSell;
@property(nonatomic, readwrite, copy, null_resettable) NSString *stopMsg;
/** Test to see if @c stopMsg has been set. */
@property(nonatomic, readwrite) BOOL hasStopMsg;

@property(nonatomic, readwrite) uint32_t lotteryType;

@property(nonatomic, readwrite) BOOL hasLotteryType;
@property(nonatomic, readwrite) uint32_t serTime;

@property(nonatomic, readwrite) BOOL hasSerTime;
@end

#pragma mark - LotterySync_Msg

typedef GPB_ENUM(LotterySync_Msg_FieldNumber) {
  LotterySync_Msg_FieldNumber_Action = 1,
  LotterySync_Msg_FieldNumber_Ct = 2,
  LotterySync_Msg_FieldNumber_Msgtype = 3,
  LotterySync_Msg_FieldNumber_LotteryType = 4,
  LotterySync_Msg_FieldNumber_LotteryInfo = 5,
};

GPB_FINAL @interface LotterySync_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t lotteryType;

@property(nonatomic, readwrite) BOOL hasLotteryType;
@property(nonatomic, readwrite, strong, null_resettable) LotterySync_LotteryInfo *lotteryInfo;
/** Test to see if @c lotteryInfo has been set. */
@property(nonatomic, readwrite) BOOL hasLotteryInfo;

@end

#pragma mark - SendContactInfo

typedef GPB_ENUM(SendContactInfo_FieldNumber) {
  SendContactInfo_FieldNumber_Retcode = 1,
  SendContactInfo_FieldNumber_Retmsg = 2,
  SendContactInfo_FieldNumber_Msg = 3,
};

GPB_FINAL @interface SendContactInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) SendContactInfo_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - SendContactInfo_Msg

typedef GPB_ENUM(SendContactInfo_Msg_FieldNumber) {
  SendContactInfo_Msg_FieldNumber_Action = 1,
  SendContactInfo_Msg_FieldNumber_Ct = 2,
  SendContactInfo_Msg_FieldNumber_Msgtype = 3,
};

GPB_FINAL @interface SendContactInfo_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@end

#pragma mark - SendRed

typedef GPB_ENUM(SendRed_FieldNumber) {
  SendRed_FieldNumber_Retcode = 1,
  SendRed_FieldNumber_Retmsg = 2,
  SendRed_FieldNumber_Msg = 3,
};

GPB_FINAL @interface SendRed : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) SendRed_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - SendRed_Msg

typedef GPB_ENUM(SendRed_Msg_FieldNumber) {
  SendRed_Msg_FieldNumber_Action = 1,
  SendRed_Msg_FieldNumber_Ct = 2,
  SendRed_Msg_FieldNumber_Msgtype = 3,
  SendRed_Msg_FieldNumber_Touid = 4,
  SendRed_Msg_FieldNumber_Ugood = 5,
  SendRed_Msg_FieldNumber_Uid = 6,
  SendRed_Msg_FieldNumber_Name = 7,
  SendRed_Msg_FieldNumber_Uname = 8,
  SendRed_Msg_FieldNumber_Equipment = 9,
  SendRed_Msg_FieldNumber_Roomnum = 10,
  SendRed_Msg_FieldNumber_Level = 11,
  SendRed_Msg_FieldNumber_Evensend = 12,
  SendRed_Msg_FieldNumber_Uhead = 13,
  SendRed_Msg_FieldNumber_VipType = 14,
  SendRed_Msg_FieldNumber_Liangname = 15,
  SendRed_Msg_FieldNumber_IsAnchor = 16,
};

GPB_FINAL @interface SendRed_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t touid;

@property(nonatomic, readwrite) BOOL hasTouid;
@property(nonatomic, readwrite) uint32_t ugood;

@property(nonatomic, readwrite) BOOL hasUgood;
@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *equipment;
/** Test to see if @c equipment has been set. */
@property(nonatomic, readwrite) BOOL hasEquipment;

@property(nonatomic, readwrite) uint32_t roomnum;

@property(nonatomic, readwrite) BOOL hasRoomnum;
@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) BOOL hasLevel;
@property(nonatomic, readwrite, copy, null_resettable) NSString *evensend;
/** Test to see if @c evensend has been set. */
@property(nonatomic, readwrite) BOOL hasEvensend;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uhead;
/** Test to see if @c uhead has been set. */
@property(nonatomic, readwrite) BOOL hasUhead;

@property(nonatomic, readwrite) uint32_t vipType;

@property(nonatomic, readwrite) BOOL hasVipType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *liangname;
/** Test to see if @c liangname has been set. */
@property(nonatomic, readwrite) BOOL hasLiangname;

@property(nonatomic, readwrite) BOOL isAnchor;

@property(nonatomic, readwrite) BOOL hasIsAnchor;
@end

#pragma mark - SendGift

typedef GPB_ENUM(SendGift_FieldNumber) {
  SendGift_FieldNumber_Retcode = 1,
  SendGift_FieldNumber_Retmsg = 2,
  SendGift_FieldNumber_Msg = 3,
};

GPB_FINAL @interface SendGift : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) SendGift_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - SendGift_GiftInfo

typedef GPB_ENUM(SendGift_GiftInfo_FieldNumber) {
  SendGift_GiftInfo_FieldNumber_Uid = 1,
  SendGift_GiftInfo_FieldNumber_Giftid = 2,
  SendGift_GiftInfo_FieldNumber_Type = 3,
  SendGift_GiftInfo_FieldNumber_Giftcount = 4,
  SendGift_GiftInfo_FieldNumber_Totalcoin = 5,
  SendGift_GiftInfo_FieldNumber_Giftname = 6,
  SendGift_GiftInfo_FieldNumber_Gifticon = 7,
  SendGift_GiftInfo_FieldNumber_Swftime = 8,
  SendGift_GiftInfo_FieldNumber_Swftype = 9,
  SendGift_GiftInfo_FieldNumber_Swf = 10,
  SendGift_GiftInfo_FieldNumber_Level = 11,
  SendGift_GiftInfo_FieldNumber_Coin = 12,
  SendGift_GiftInfo_FieldNumber_Votestotal = 13,
  SendGift_GiftInfo_FieldNumber_Strvotestotal = 14,
};

GPB_FINAL @interface SendGift_GiftInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite) uint32_t giftid;

@property(nonatomic, readwrite) BOOL hasGiftid;
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) uint32_t giftcount;

@property(nonatomic, readwrite) BOOL hasGiftcount;
@property(nonatomic, readwrite) uint32_t totalcoin;

@property(nonatomic, readwrite) BOOL hasTotalcoin;
@property(nonatomic, readwrite, copy, null_resettable) NSString *giftname;
/** Test to see if @c giftname has been set. */
@property(nonatomic, readwrite) BOOL hasGiftname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gifticon;
/** Test to see if @c gifticon has been set. */
@property(nonatomic, readwrite) BOOL hasGifticon;

@property(nonatomic, readwrite) uint32_t swftime;

@property(nonatomic, readwrite) BOOL hasSwftime;
@property(nonatomic, readwrite) uint32_t swftype;

@property(nonatomic, readwrite) BOOL hasSwftype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *swf;
/** Test to see if @c swf has been set. */
@property(nonatomic, readwrite) BOOL hasSwf;

@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) BOOL hasLevel;
@property(nonatomic, readwrite) uint32_t coin;

@property(nonatomic, readwrite) BOOL hasCoin;
@property(nonatomic, readwrite) uint32_t votestotal;

@property(nonatomic, readwrite) BOOL hasVotestotal;
@property(nonatomic, readwrite, copy, null_resettable) NSString *strvotestotal;
/** Test to see if @c strvotestotal has been set. */
@property(nonatomic, readwrite) BOOL hasStrvotestotal;

@end

#pragma mark - SendGift_Msg

typedef GPB_ENUM(SendGift_Msg_FieldNumber) {
  SendGift_Msg_FieldNumber_Action = 1,
  SendGift_Msg_FieldNumber_Ct = 2,
  SendGift_Msg_FieldNumber_Msgtype = 3,
  SendGift_Msg_FieldNumber_Uid = 4,
  SendGift_Msg_FieldNumber_Uname = 5,
  SendGift_Msg_FieldNumber_Equipment = 6,
  SendGift_Msg_FieldNumber_Roomnum = 7,
  SendGift_Msg_FieldNumber_Level = 8,
  SendGift_Msg_FieldNumber_Evensend = 9,
  SendGift_Msg_FieldNumber_Uhead = 10,
  SendGift_Msg_FieldNumber_VipType = 11,
  SendGift_Msg_FieldNumber_Liangname = 12,
  SendGift_Msg_FieldNumber_Ifpk = 13,
  SendGift_Msg_FieldNumber_Pkuid1 = 14,
  SendGift_Msg_FieldNumber_Pkuid2 = 15,
  SendGift_Msg_FieldNumber_Pktotal1 = 16,
  SendGift_Msg_FieldNumber_Pktotal2 = 17,
};

GPB_FINAL @interface SendGift_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite, strong, null_resettable) SendGift_GiftInfo *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *equipment;
/** Test to see if @c equipment has been set. */
@property(nonatomic, readwrite) BOOL hasEquipment;

@property(nonatomic, readwrite) uint32_t roomnum;

@property(nonatomic, readwrite) BOOL hasRoomnum;
@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) BOOL hasLevel;
@property(nonatomic, readwrite, copy, null_resettable) NSString *evensend;
/** Test to see if @c evensend has been set. */
@property(nonatomic, readwrite) BOOL hasEvensend;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uhead;
/** Test to see if @c uhead has been set. */
@property(nonatomic, readwrite) BOOL hasUhead;

@property(nonatomic, readwrite) uint32_t vipType;

@property(nonatomic, readwrite) BOOL hasVipType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *liangname;
/** Test to see if @c liangname has been set. */
@property(nonatomic, readwrite) BOOL hasLiangname;

@property(nonatomic, readwrite) uint32_t ifpk;

@property(nonatomic, readwrite) BOOL hasIfpk;
@property(nonatomic, readwrite) uint32_t pkuid1;

@property(nonatomic, readwrite) BOOL hasPkuid1;
@property(nonatomic, readwrite) uint32_t pkuid2;

@property(nonatomic, readwrite) BOOL hasPkuid2;
@property(nonatomic, readwrite) uint32_t pktotal1;

@property(nonatomic, readwrite) BOOL hasPktotal1;
@property(nonatomic, readwrite) uint32_t pktotal2;

@property(nonatomic, readwrite) BOOL hasPktotal2;
@end

#pragma mark - SendBarrage

typedef GPB_ENUM(SendBarrage_FieldNumber) {
  SendBarrage_FieldNumber_Retcode = 1,
  SendBarrage_FieldNumber_Retmsg = 2,
  SendBarrage_FieldNumber_Msg = 3,
};

GPB_FINAL @interface SendBarrage : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) SendBarrage_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - SendBarrage_CTStruct

typedef GPB_ENUM(SendBarrage_CTStruct_FieldNumber) {
  SendBarrage_CTStruct_FieldNumber_Uid = 1,
  SendBarrage_CTStruct_FieldNumber_Content = 2,
  SendBarrage_CTStruct_FieldNumber_Giftid = 3,
  SendBarrage_CTStruct_FieldNumber_Giftcount = 4,
  SendBarrage_CTStruct_FieldNumber_Totalcoin = 5,
  SendBarrage_CTStruct_FieldNumber_Giftname = 6,
  SendBarrage_CTStruct_FieldNumber_Gifticon = 7,
  SendBarrage_CTStruct_FieldNumber_Level = 8,
  SendBarrage_CTStruct_FieldNumber_Coin = 9,
  SendBarrage_CTStruct_FieldNumber_Votestotal = 10,
  SendBarrage_CTStruct_FieldNumber_Strvotestotal = 11,
};

GPB_FINAL @interface SendBarrage_CTStruct : GPBMessage

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite) uint32_t giftid;

@property(nonatomic, readwrite) BOOL hasGiftid;
@property(nonatomic, readwrite) uint32_t giftcount;

@property(nonatomic, readwrite) BOOL hasGiftcount;
@property(nonatomic, readwrite) uint32_t totalcoin;

@property(nonatomic, readwrite) BOOL hasTotalcoin;
@property(nonatomic, readwrite, copy, null_resettable) NSString *giftname;
/** Test to see if @c giftname has been set. */
@property(nonatomic, readwrite) BOOL hasGiftname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gifticon;
/** Test to see if @c gifticon has been set. */
@property(nonatomic, readwrite) BOOL hasGifticon;

@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) BOOL hasLevel;
@property(nonatomic, readwrite) uint32_t coin;

@property(nonatomic, readwrite) BOOL hasCoin;
@property(nonatomic, readwrite) uint32_t votestotal;

@property(nonatomic, readwrite) BOOL hasVotestotal;
@property(nonatomic, readwrite, copy, null_resettable) NSString *strvotestotal;
/** Test to see if @c strvotestotal has been set. */
@property(nonatomic, readwrite) BOOL hasStrvotestotal;

@end

#pragma mark - SendBarrage_Msg

typedef GPB_ENUM(SendBarrage_Msg_FieldNumber) {
  SendBarrage_Msg_FieldNumber_Action = 1,
  SendBarrage_Msg_FieldNumber_Msgtype = 2,
  SendBarrage_Msg_FieldNumber_Level = 3,
  SendBarrage_Msg_FieldNumber_Uname = 4,
  SendBarrage_Msg_FieldNumber_Uid = 5,
  SendBarrage_Msg_FieldNumber_Uhead = 6,
  SendBarrage_Msg_FieldNumber_Ct = 7,
};

GPB_FINAL @interface SendBarrage_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) BOOL hasLevel;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uhead;
/** Test to see if @c uhead has been set. */
@property(nonatomic, readwrite) BOOL hasUhead;

@property(nonatomic, readwrite, strong, null_resettable) SendBarrage_CTStruct *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@end

#pragma mark - changeLive

typedef GPB_ENUM(changeLive_FieldNumber) {
  changeLive_FieldNumber_Retcode = 1,
  changeLive_FieldNumber_Retmsg = 2,
  changeLive_FieldNumber_Msg = 3,
};

GPB_FINAL @interface changeLive : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) changeLive_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - changeLive_Msg

typedef GPB_ENUM(changeLive_Msg_FieldNumber) {
  changeLive_Msg_FieldNumber_Action = 1,
  changeLive_Msg_FieldNumber_Msgtype = 2,
  changeLive_Msg_FieldNumber_TypeVal = 3,
  changeLive_Msg_FieldNumber_Type = 4,
  changeLive_Msg_FieldNumber_RoomType = 5,
  changeLive_Msg_FieldNumber_Msg = 6,
};

GPB_FINAL @interface changeLive_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *typeVal;
/** Test to see if @c typeVal has been set. */
@property(nonatomic, readwrite) BOOL hasTypeVal;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;
/** Test to see if @c type has been set. */
@property(nonatomic, readwrite) BOOL hasType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomType;
/** Test to see if @c roomType has been set. */
@property(nonatomic, readwrite) BOOL hasRoomType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - updateVotes

typedef GPB_ENUM(updateVotes_FieldNumber) {
  updateVotes_FieldNumber_Retcode = 1,
  updateVotes_FieldNumber_Retmsg = 2,
  updateVotes_FieldNumber_Msg = 3,
};

GPB_FINAL @interface updateVotes : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) updateVotes_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - updateVotes_Msg

typedef GPB_ENUM(updateVotes_Msg_FieldNumber) {
  updateVotes_Msg_FieldNumber_Action = 1,
  updateVotes_Msg_FieldNumber_Msgtype = 2,
  updateVotes_Msg_FieldNumber_Votes = 3,
  updateVotes_Msg_FieldNumber_Uid = 4,
  updateVotes_Msg_FieldNumber_Isfirst = 5,
  updateVotes_Msg_FieldNumber_Strvotestotal = 6,
};

GPB_FINAL @interface updateVotes_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite) float votes;

@property(nonatomic, readwrite) BOOL hasVotes;
@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite) uint32_t isfirst;

@property(nonatomic, readwrite) BOOL hasIsfirst;
@property(nonatomic, readwrite, copy, null_resettable) NSString *strvotestotal;
/** Test to see if @c strvotestotal has been set. */
@property(nonatomic, readwrite) BOOL hasStrvotestotal;

@end

#pragma mark - ShutUpUser

typedef GPB_ENUM(ShutUpUser_FieldNumber) {
  ShutUpUser_FieldNumber_Retcode = 1,
  ShutUpUser_FieldNumber_Retmsg = 2,
  ShutUpUser_FieldNumber_Msg = 3,
};

GPB_FINAL @interface ShutUpUser : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) ShutUpUser_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - ShutUpUser_Msg

typedef GPB_ENUM(ShutUpUser_Msg_FieldNumber) {
  ShutUpUser_Msg_FieldNumber_Action = 1,
  ShutUpUser_Msg_FieldNumber_Msgtype = 2,
  ShutUpUser_Msg_FieldNumber_Ct = 3,
  ShutUpUser_Msg_FieldNumber_Uid = 4,
  ShutUpUser_Msg_FieldNumber_Touid = 5,
};

GPB_FINAL @interface ShutUpUser_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite) uint32_t touid;

@property(nonatomic, readwrite) BOOL hasTouid;
@end

#pragma mark - setAdmin

typedef GPB_ENUM(setAdmin_FieldNumber) {
  setAdmin_FieldNumber_Retcode = 1,
  setAdmin_FieldNumber_Retmsg = 2,
  setAdmin_FieldNumber_Msg = 3,
};

GPB_FINAL @interface setAdmin : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) setAdmin_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - setAdmin_Msg

typedef GPB_ENUM(setAdmin_Msg_FieldNumber) {
  setAdmin_Msg_FieldNumber_Action = 1,
  setAdmin_Msg_FieldNumber_Msgtype = 2,
  setAdmin_Msg_FieldNumber_Ct = 3,
  setAdmin_Msg_FieldNumber_Uid = 4,
  setAdmin_Msg_FieldNumber_Uname = 5,
  setAdmin_Msg_FieldNumber_Touid = 6,
  setAdmin_Msg_FieldNumber_Touname = 7,
};

GPB_FINAL @interface setAdmin_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite) uint32_t touid;

@property(nonatomic, readwrite) BOOL hasTouid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *touname;
/** Test to see if @c touname has been set. */
@property(nonatomic, readwrite) BOOL hasTouname;

@end

#pragma mark - BuyGuard

typedef GPB_ENUM(BuyGuard_FieldNumber) {
  BuyGuard_FieldNumber_Retcode = 1,
  BuyGuard_FieldNumber_Retmsg = 2,
  BuyGuard_FieldNumber_Msg = 3,
};

GPB_FINAL @interface BuyGuard : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) BuyGuard_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - BuyGuard_Msg

typedef GPB_ENUM(BuyGuard_Msg_FieldNumber) {
  BuyGuard_Msg_FieldNumber_Action = 1,
  BuyGuard_Msg_FieldNumber_Msgtype = 2,
  BuyGuard_Msg_FieldNumber_Ct = 3,
  BuyGuard_Msg_FieldNumber_Uid = 4,
  BuyGuard_Msg_FieldNumber_Uname = 5,
  BuyGuard_Msg_FieldNumber_Uhead = 6,
  BuyGuard_Msg_FieldNumber_Votestotal = 7,
  BuyGuard_Msg_FieldNumber_GuardNums = 8,
  BuyGuard_Msg_FieldNumber_GuardType = 9,
  BuyGuard_Msg_FieldNumber_Strvotestotal = 10,
};

GPB_FINAL @interface BuyGuard_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uhead;
/** Test to see if @c uhead has been set. */
@property(nonatomic, readwrite) BOOL hasUhead;

@property(nonatomic, readwrite) uint32_t votestotal;

@property(nonatomic, readwrite) BOOL hasVotestotal;
@property(nonatomic, readwrite) uint32_t guardNums;

@property(nonatomic, readwrite) BOOL hasGuardNums;
@property(nonatomic, readwrite) uint32_t guardType;

@property(nonatomic, readwrite) BOOL hasGuardType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *strvotestotal;
/** Test to see if @c strvotestotal has been set. */
@property(nonatomic, readwrite) BOOL hasStrvotestotal;

@end

#pragma mark - KickUser

typedef GPB_ENUM(KickUser_FieldNumber) {
  KickUser_FieldNumber_Retcode = 1,
  KickUser_FieldNumber_Retmsg = 2,
  KickUser_FieldNumber_Msg = 3,
};

GPB_FINAL @interface KickUser : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) KickUser_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - KickUser_Msg

typedef GPB_ENUM(KickUser_Msg_FieldNumber) {
  KickUser_Msg_FieldNumber_Action = 1,
  KickUser_Msg_FieldNumber_Msgtype = 2,
  KickUser_Msg_FieldNumber_Ct = 3,
  KickUser_Msg_FieldNumber_Uid = 4,
  KickUser_Msg_FieldNumber_Touid = 5,
  KickUser_Msg_FieldNumber_Showid = 6,
  KickUser_Msg_FieldNumber_Uname = 7,
};

GPB_FINAL @interface KickUser_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@property(nonatomic, readwrite) uint32_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
@property(nonatomic, readwrite) uint32_t touid;

@property(nonatomic, readwrite) BOOL hasTouid;
@property(nonatomic, readwrite) uint32_t showid;

@property(nonatomic, readwrite) BOOL hasShowid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uname;
/** Test to see if @c uname has been set. */
@property(nonatomic, readwrite) BOOL hasUname;

@end

#pragma mark - light

typedef GPB_ENUM(light_FieldNumber) {
  light_FieldNumber_Retcode = 1,
  light_FieldNumber_Retmsg = 2,
  light_FieldNumber_Msg = 3,
};

GPB_FINAL @interface light : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) light_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - light_Msg

typedef GPB_ENUM(light_Msg_FieldNumber) {
  light_Msg_FieldNumber_Action = 1,
  light_Msg_FieldNumber_Msgtype = 2,
  light_Msg_FieldNumber_Ct = 3,
};

GPB_FINAL @interface light_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ct;
/** Test to see if @c ct has been set. */
@property(nonatomic, readwrite) BOOL hasCt;

@end

#pragma mark - stopLive

typedef GPB_ENUM(stopLive_FieldNumber) {
  stopLive_FieldNumber_Retcode = 1,
  stopLive_FieldNumber_Retmsg = 2,
  stopLive_FieldNumber_Msg = 3,
};

GPB_FINAL @interface stopLive : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) stopLive_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - stopLive_Msg

typedef GPB_ENUM(stopLive_Msg_FieldNumber) {
  stopLive_Msg_FieldNumber_Action = 1,
  stopLive_Msg_FieldNumber_Msgtype = 2,
};

GPB_FINAL @interface stopLive_Msg : GPBMessage

@property(nonatomic, readwrite) uint32_t action;

@property(nonatomic, readwrite) BOOL hasAction;
@property(nonatomic, readwrite) uint32_t msgtype;

@property(nonatomic, readwrite) BOOL hasMsgtype;
@end

#pragma mark - AppTopNotice

typedef GPB_ENUM(AppTopNotice_FieldNumber) {
  AppTopNotice_FieldNumber_Retcode = 1,
  AppTopNotice_FieldNumber_Retmsg = 2,
  AppTopNotice_FieldNumber_Msg = 3,
};

GPB_FINAL @interface AppTopNotice : GPBMessage

@property(nonatomic, readwrite) uint32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *retmsg;
/** Test to see if @c retmsg has been set. */
@property(nonatomic, readwrite) BOOL hasRetmsg;

@property(nonatomic, readwrite, strong, null_resettable) AppTopNotice_Msg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - AppTopNotice_Msg

typedef GPB_ENUM(AppTopNotice_Msg_FieldNumber) {
  AppTopNotice_Msg_FieldNumber_NoticeTitle = 1,
  AppTopNotice_Msg_FieldNumber_NoticeMainIcon = 2,
  AppTopNotice_Msg_FieldNumber_NoticeContent = 3,
  AppTopNotice_Msg_FieldNumber_NoticeSubIcon = 4,
  AppTopNotice_Msg_FieldNumber_NoticeScheme = 5,
};

GPB_FINAL @interface AppTopNotice_Msg : GPBMessage

/** 消息标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *noticeTitle;
/** Test to see if @c noticeTitle has been set. */
@property(nonatomic, readwrite) BOOL hasNoticeTitle;

/** 消息源图标(如果为空字符串 则显示App图标) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *noticeMainIcon;
/** Test to see if @c noticeMainIcon has been set. */
@property(nonatomic, readwrite) BOOL hasNoticeMainIcon;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *noticeContent;
/** Test to see if @c noticeContent has been set. */
@property(nonatomic, readwrite) BOOL hasNoticeContent;

/** 消息内容图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *noticeSubIcon;
/** Test to see if @c noticeSubIcon has been set. */
@property(nonatomic, readwrite) BOOL hasNoticeSubIcon;

/** 消息跳转 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *noticeScheme;
/** Test to see if @c noticeScheme has been set. */
@property(nonatomic, readwrite) BOOL hasNoticeScheme;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
